### ISSUE TITLE
YouTube Music CSS not being applied

### ISSUE THREAD

**Issue by NNowakowski** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3564]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:** Windows 10

**GPMDP Version:** 4.6.1

**Issue Descriptions:** I'm trying to apply custom styles to the YouTube Music player, however it isn't being picked up. The CSS I'm using is valid and works within Chrome:
```css
/* Moves the song info to the left */
.middle-controls.style-scope.ytmusic-player-bar {
  justify-content: flex-start;
}

/* Hides the buttons next to the song info */
.middle-controls-buttons.style-scope.ytmusic-player-bar {
  visibility: hidden;
}
```
I've selected the file for both the main window and the Google Music section, however both of those don't seem to work for it. Is it not possible to use custom styles for YouTube Music yet?

**Steps to Reproduce:** Create a stylesheet with the mentioned code. Select the file for both filepickers. Click reload styles.
